# Generated by Django 3.2.25 on 2026-08-01 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='收件人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='收件人手机号')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区/县')),
                ('detail_address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='是否为默认地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '地址簿',
                'verbose_name_plural': '地址簿',
                'db_table': 'Address',
                'ordering': ['-is_default', '-update_time'],
            },
        ),
    ]
