[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --cov-config=pytest.ini
# 忽略版本warning问题
filterwarnings =
    ignore:.*Python 3.8 is no longer supported.*:UserWarning
    ignore:.*Python 3.8 is no longer supported.*:DeprecationWarning

# 覆盖率过滤规则
[coverage:run]
omit =
    */venv/*
    */tests/*
    
    */migrations/*
    core/settings.py
    core/wsgi.py
    core/asgi.py
    manage.py
    
    */__init__.py
    */admin.py
    */apps.py
    */tests.py
    *urls.py
    conftest.py