# Generated by Django 3.2 on 2026-07-14 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('status', models.IntegerField(choices=[(0, '未知'), (10, '待付款'), (20, '待发货'), (30, '已发货'), (40, '已收货'), (50, '已取消')], default=10, verbose_name='订单状态')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='运费')),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='优惠金额')),
                ('payment_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付金额')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('note', models.TextField(blank=True, verbose_name='订单备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下单时单价')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product')),
            ],
            options={
                'verbose_name': '订单清单',
                'verbose_name_plural': '订单清单',
                'db_table': 'orderitem',
            },
        ),
    ]
