# Generated by Django 3.2.25 on 2026-08-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trade_no",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="支付宝交易流水号"
            ),
        ),
    ]
